### ISSUE TITLE
API does not allow resource type id with dot

### ISSUE THREAD

**Issue by vroldanbet** [zalando-stups/mint-storage#31]
If a request to the api is done with a resource_type_id that contains dots on it, the API will return 400 Bad Request:

```
localhost:8080/apps?resource_type_id=resource.with-dots&scope_id=read
```
```json
{
"message": "Value \"resource.with-dots\" in query->resource_type_id (not required) cannot be used as type 'string' because it does not match the given pattern '^[a-z][a-z0-9-_]*[a-z0-9]$'.",
"details": null
}
```

**Comment by hjacobs** [comment]
@vroldanbet this is related to our scopes concept as described on http://zalando.github.io/restful-api-guidelines/security/Security.html => resource types are currently application IDs which do not contain dots. We probably need to adapt the whole section for Zalando Platform IAM.

**Comment by hjacobs** [comment]
OK, sorry, I see that it does not fit the existing documentation on http://zalando.github.io/restful-api-guidelines/security/Security.html

The format `<application-id>.<resource-id>.<access-type>` is not supported because only one dot is allowed.

**Comment by ePaul** [comment]
I also just hit this problem. We currently have resource names with dots in the name, so searching for them here should be allowed.

This also surfaces in the Yourturn frontend, when trying to see which services have such a scope assigned, it says "no applications with scope".
